// Classes from libraries that the Compose compiler should treat as stable.
kotlin.time.Instant
kotlin.time.Duration
kotlinx.datetime.LocalTime
kotlinx.datetime.DayOfWeek
kotlinx.datetime.TimeZone
kotlinx.collections.immutable.*
